import { useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';

interface TicketData {
  eventTitle: string;
  venue: string;
  city: string;
  date: string;
  time: string;
  seats: string[];
  totalPrice: number;
  bookingId: string;
  parking?: {
    zone: string;
    slotNumber: number;
    vehicleType: string;
    fee: number;
  } | null;
}

function drawTicket(canvas: HTMLCanvasElement, data: TicketData) {
  const ctx = canvas.getContext('2d')!;
  const W = 900;
  const H = 480;
  canvas.width = W;
  canvas.height = H;

  // Background
  const bg = ctx.createLinearGradient(0, 0, W, H);
  bg.addColorStop(0, '#0f0f23');
  bg.addColorStop(1, '#1a1a3e');
  ctx.fillStyle = bg;
  roundRect(ctx, 0, 0, W, H, 20);
  ctx.fill();

  // Left accent bar
  const accent = ctx.createLinearGradient(0, 0, 0, H);
  accent.addColorStop(0, '#7c3aed');
  accent.addColorStop(1, '#2563eb');
  ctx.fillStyle = accent;
  roundRect(ctx, 0, 0, 10, H, 20);
  ctx.fill();
  ctx.fillRect(5, 0, 10, H);

  // Dashed tear line
  ctx.setLineDash([8, 6]);
  ctx.strokeStyle = '#334155';
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(620, 20);
  ctx.lineTo(620, H - 20);
  ctx.stroke();
  ctx.setLineDash([]);

  // Tear circles
  ctx.fillStyle = '#0a0a1a';
  ctx.beginPath(); ctx.arc(620, 0, 14, 0, Math.PI * 2); ctx.fill();
  ctx.beginPath(); ctx.arc(620, H, 14, 0, Math.PI * 2); ctx.fill();

  // ── LEFT SIDE ──
  // "EVENTHUB" header
  ctx.fillStyle = '#7c3aed';
  ctx.font = 'bold 13px "Inter", system-ui, sans-serif';
  ctx.letterSpacing = '4px';
  ctx.fillText('E V E N T H U B', 40, 46);

  // Event title
  ctx.fillStyle = '#f1f5f9';
  ctx.font = 'bold 28px "Inter", system-ui, sans-serif';
  const titleLines = wrapText(ctx, data.eventTitle, 540);
  titleLines.forEach((line, i) => {
    ctx.fillText(line, 40, 90 + i * 34);
  });

  const infoY = 90 + titleLines.length * 34 + 16;

  // Venue & city
  ctx.fillStyle = '#94a3b8';
  ctx.font = '15px "Inter", system-ui, sans-serif';
  ctx.fillText(`📍 ${data.venue}, ${data.city}`, 40, infoY);

  // Date & time
  ctx.fillText(`📅 ${data.date}  ·  🕐 ${data.time}`, 40, infoY + 28);

  // Seats
  const seatStr = data.seats.join(', ');
  ctx.fillStyle = '#e2e8f0';
  ctx.font = 'bold 15px "Inter", system-ui, sans-serif';
  ctx.fillText('Seats', 40, infoY + 70);
  ctx.fillStyle = '#94a3b8';
  ctx.font = '14px "Inter", system-ui, sans-serif';
  ctx.fillText(seatStr, 110, infoY + 70);

  // Parking
  if (data.parking) {
    ctx.fillStyle = '#e2e8f0';
    ctx.font = 'bold 15px "Inter", system-ui, sans-serif';
    ctx.fillText('Parking', 40, infoY + 98);
    ctx.fillStyle = '#94a3b8';
    ctx.font = '14px "Inter", system-ui, sans-serif';
    ctx.fillText(`Zone ${data.parking.zone} · Slot #${data.parking.slotNumber} · ${data.parking.vehicleType}`, 120, infoY + 98);
  }

  // Total price box
  const priceBoxY = H - 80;
  ctx.fillStyle = 'rgba(124, 58, 237, 0.15)';
  roundRect(ctx, 40, priceBoxY, 200, 48, 10);
  ctx.fill();
  ctx.fillStyle = '#a78bfa';
  ctx.font = 'bold 22px "Inter", system-ui, sans-serif';
  ctx.fillText(`₹${data.totalPrice.toLocaleString('en-IN')}`, 60, priceBoxY + 32);
  ctx.fillStyle = '#64748b';
  ctx.font = '11px "Inter", system-ui, sans-serif';
  ctx.fillText('TOTAL PAID', 155, priceBoxY + 32);

  // ── RIGHT SIDE ──
  // QR placeholder (stylized square)
  const qrX = 660;
  const qrY = 50;
  const qrSize = 130;
  ctx.fillStyle = '#ffffff';
  roundRect(ctx, qrX, qrY, qrSize, qrSize, 8);
  ctx.fill();

  // Draw a fake QR pattern
  drawQRPattern(ctx, qrX + 10, qrY + 10, qrSize - 20, data.bookingId);

  // Booking ID
  ctx.fillStyle = '#94a3b8';
  ctx.font = '11px "Inter", system-ui, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('BOOKING ID', qrX + qrSize / 2, qrY + qrSize + 26);
  ctx.fillStyle = '#e2e8f0';
  ctx.font = 'bold 12px "Courier New", monospace';
  ctx.fillText(data.bookingId.slice(0, 16), qrX + qrSize / 2, qrY + qrSize + 44);

  // Admit count
  ctx.fillStyle = '#7c3aed';
  ctx.font = 'bold 48px "Inter", system-ui, sans-serif';
  ctx.fillText(String(data.seats.length), qrX + qrSize / 2, H - 100);
  ctx.fillStyle = '#94a3b8';
  ctx.font = '13px "Inter", system-ui, sans-serif';
  ctx.fillText(data.seats.length === 1 ? 'ADMIT ONE' : 'ADMIT', qrX + qrSize / 2, H - 70);

  ctx.textAlign = 'left';

  // Footer
  ctx.fillStyle = '#334155';
  ctx.font = '10px "Inter", system-ui, sans-serif';
  ctx.fillText('Generated by EventHub · eventhub.app', 40, H - 18);
}

function drawQRPattern(ctx: CanvasRenderingContext2D, x: number, y: number, size: number, seed: string) {
  const cells = 11;
  const cellSize = size / cells;
  // Use the seed to generate a deterministic pattern
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = (hash << 5) - hash + seed.charCodeAt(i);
    hash |= 0;
  }

  for (let r = 0; r < cells; r++) {
    for (let c = 0; c < cells; c++) {
      // Corner squares (QR finder patterns)
      const isCorner =
        (r < 3 && c < 3) || (r < 3 && c >= cells - 3) || (r >= cells - 3 && c < 3);
      const isCornerBorder =
        (r < 3 && c < 3) || (r < 3 && c >= cells - 3) || (r >= cells - 3 && c < 3);

      if (isCorner) {
        const isEdge = r === 0 || r === 2 || c === 0 || c === 2 ||
                       c === cells - 1 || c === cells - 3 || r === cells - 1 || r === cells - 3;
        const isCenter = (r === 1 && c === 1) || (r === 1 && c === cells - 2) || (r === cells - 2 && c === 1);
        ctx.fillStyle = (isEdge || isCenter) ? '#1a1a3e' : '#ffffff';
      } else {
        // Pseudo-random fill based on hash
        const val = (hash + r * 17 + c * 31) % 7;
        ctx.fillStyle = val < 3 ? '#1a1a3e' : '#ffffff';
      }
      ctx.fillRect(x + c * cellSize, y + r * cellSize, cellSize, cellSize);
    }
  }
}

function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export default function TicketDownload({ data }: { data: TicketData }) {
  const handleDownload = useCallback(() => {
    const canvas = document.createElement('canvas');
    drawTicket(canvas, data);

    const link = document.createElement('a');
    link.download = `EventHub-Ticket-${data.bookingId.slice(0, 8)}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }, [data]);

  return (
    <Button onClick={handleDownload} variant="outline" className="gap-2">
      <Download className="h-4 w-4" />
      Download Ticket
    </Button>
  );
}
